language: cpp

notifications:
  email: false

addons:
  apt:
    packages:
      - libc6-i386 #To execute 32bit binaries on 64bit systems

script:
  - ./premake/linux/premake5 gmake
  - pushd .build/projects/
  - make
  - popd
  - pushd .build/bin/Debug/
  - enter
  - popd

